---

- name : create backup directory
  file: state=directory path=/home/ec2-user/app-backup 
 
- name: Stop Tomcat server
  service:
    name: tomcat
    state: stopped
  become: yes

- name: Back up current deployed artifact
  become: yes
  copy:
     src: "/opt/tomcat/webapps/ROOT/index.html"
     dest: "/home/ec2-user/app-backup/index.html-{{ date }}"
     remote_src: yes

- name: Copy Artifact 
  become: yes
  copy:
    src: "index.html"
    dest: /opt/tomcat/webapps/ROOT/

- name: Start Tomcat Server
  service:
    name: tomcat
    state: started
  become: yes

